pipelines:
  - name: conditional_pipeline
    steps:

      - name: slo_evaluation
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook
        execution:
          onExecute:
            - echo 'step: slo_evaluation'

      - name: manual_approval
        type: Bash
        configuration:
          inputSteps:
            - name: slo_evaluation
              status:
                - success
        execution:
          onExecute:
            - echo 'step: manual_approval'

      - name: promote_build
        type: Bash
        configuration:
          inputSteps:
            - name: slo_evaluation
              status:
                - success
        execution:
          onExecute:
            - echo 'step: promote_build'
