pipelines:
  - name: slo_pipeline
    configuration:
      environmentVariables:
        readOnly:
          KEPTN_PROJECT: "demo"
          KEPTN_SERVICE: "casdemoapp"
          KEPTN_STAGE: "production"
          KEPTN_AUTOMATION_IMAGE: "dtdemos/keptn-automation:0.2.1"

    steps:
    - name: slo_quality_gate
      type: Bash
      configuration:
        environmentVariables:
          LABELS: "runId=$run_id,executedBy=Jfrog,Job=$step_url"
          EVALUATION_RULE: "pass_on_warning"
        affinityGroup: slo_quality_gate
        integrations:
          - name: keptnCred
        inputSteps:
          - name: Send_Finish_Event
      execution:
        onExecute:
          - |
            docker run  \
                --env EVALUATION_RULE=$EVALUATION_RULE \
                --env KEPTN_BASE_URL=$int_keptnCred_BASE_URL \
                --env KEPTN_API_TOKEN=$int_keptnCred_API_TOKEN \
                --env KEPTN_PROJECT=$KEPTN_PROJECT \
                --env KEPTN_SERVICE=$KEPTN_SERVICE \
                --env KEPTN_STAGE=$KEPTN_STAGE \
                --env LABELS=$LABELS \
                $KEPTN_AUTOMATION_IMAGE \
                slo-evaluation.sh

    steps:
    - name: slo_quality_gate_with_mount
      type: Bash
      configuration:
        environmentVariables:
          LABELS: "runId=$run_id,executedBy=Jfrog,Job=$step_url"
          EVALUATION_RULE: "pass_on_warning"
        affinityGroup: slo_quality_gate
        integrations:
          - name: keptnCred
        inputSteps:
          - name: Send_Finish_Event
      execution:
        onExecute:
          - |
            docker run  \
                --env EVALUATION_RULE=$EVALUATION_RULE \
                --env KEPTN_BASE_URL=$int_keptnCred_BASE_URL \
                --env KEPTN_API_TOKEN=$int_keptnCred_API_TOKEN \
                --env KEPTN_PROJECT=$KEPTN_PROJECT \
                --env KEPTN_SERVICE=$KEPTN_SERVICE \
                --env KEPTN_STAGE=$KEPTN_STAGE \
                --env LABELS=$LABELS \
                -v $res_gitRepo_resourcePath:/slo_result \
                $KEPTN_AUTOMATION_IMAGE \
                slo-evaluation.sh
            echo "Show slo-evaluation-result.json"
            cat slo-evaluation-result.json
