apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "demo-webhook"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "mysequence"
        tasks: 
        - name: "mytask-interactive"
        - name: "evaluation"
          properties:
            timeframe: "5m"
        - name: approval
          properties: 
            pass: manual 
            warning: manual
