apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.mytask-interactive.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"project\":\"{{.data.project}}\",\"service\
          \":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"shkeptnconte\
          xt\":\"{{.shkeptncontext}}\",\"id\":\"{{.id}}\"}'
          https://hello:hello@hkt-pipelines-api.jfrog.io/v1/projectIntegrations\
          /13/hook"
      subscriptionID: 82deaa9a-a719-4ed5-a0fa-4f9c08433eb6
